name: Antibytes CI - Publish Rolling Release

on:
  workflow_dispatch:
    tags:
      - 'v*'

jobs:
  publish-rolling-release:

    runs-on: ubuntu-latest

    env:
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_USERNAME }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_TOKEN }}

    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Restore BuildCache
        uses: actions/cache/restore@v4
        with:
          path: '**/.gradle/build-cache/**'
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.sha }}
            ${{ runner.os }}-build-

      - name: Install Bison
        shell: bash
        run: sudo apt-get install -y bison
      - name: Build
        run: ./gradlew build -x check
      - name: Publish to Rolling Release Repository
        run: ./gradlew publishRollingRelease --no-configuration-cache --no-parallel
