name: Antibytes CI - Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-release:

    runs-on: ubuntu-latest

    env:
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_USERNAME }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_TOKEN }}

    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Install Bison
        shell: bash
        run: sudo apt-get install -y bison
      - name: Validate Plugins
        run: ./gradlew validatePlugins
      - name: Cleanup
        run: ./gradlew clean
      - name: Build
        run: ./gradlew build
      - name: Publish to Release Repository
        run: ./gradlew publishRelease
